### ISSUE TITLE
esp8266 support

### ISSUE THREAD

**Issue by probonopd** [MajicDesigns/MD_MIDIFile#24]
Is it possible to use MD_MIDIFile to play files from its built-in [LittleFS filesystem](https://arduino-esp8266.readthedocs.io/en/latest/filesystem.html#spiffs-deprecation-warning) rather than a SD card?

**Comment by MajicDesigns** [comment]
In principle I suppose so. As long as the new file system supports the same types of calls to open/close files, read, seek, etc it should be straightforward to replace the SD library with LittleFS calls.
